[package]
name = "cdd"
version = "0.1.0"
edition = "2018"

[dependencies]
structopt = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
dirs = "1.0"

[lib]

[[bin]]
name = "cdd"
