[package]
name = "cdd"
authors = ["Samuel Marks <@SamuelMarks>", "Rob Saunders <rob@wearebrandnew.com>"]
version = "0.0.1"
license = "Apache-2.0 OR MIT"
edition = "2018"

[dependencies]
structopt = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
dirs = "1.0"
colored = "1.7"
log = "0.4"
simplelog = "0.7.3"
failure = "0.1.5"

[lib]

[[bin]]
name = "cdd"
