---
name: default project
version: 0.0.1
description: description
author: me@me.com
openapi: openapi.yaml
auth: rfc6749
components:
  todo_list:
    tests: true
    routes: true
    validation: true
    models: true
  messaging:
    tests: true
    routes: true
    validation: true
    models: true